package project;

import javax.swing.JPanel;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.util.HashMap;

public class MapPanel extends JPanel implements ActionListener{

	public enum Continent{
		WORLD, NORTH_AMERICA, SOUTH_AMERICA, EUROPE, AFRICA, ASIA;
	}
	
	public enum MapMode{
		ECONOMIC, HEALTH; //TODO: rename later as appropriate to content?
	}
	
	//to make Eclipse shut up about the warning
	private static final long serialVersionUID = 1l;
	
	private DataManager worldData;
	private Continent currentView;//which continent are we looking at?
	private String currentCountry;//what country are we looking at right now?
	private MapMode currentMapMode;//what mode is the map in?
	private HashMap<String, AppButton> buttons;//a hash of all the buttons for the countries
	
	/**
	 * Creates a new MapPanel based on data from the given DataManager.
	 * 
	 * @param newWorldData the DataManager to load data from
	 */
	public MapPanel(DataManager newWorldData){
		//TODO: do Swing set up here as necessary
		//ie width, height setting, etc
		
		//assign DataManager
		worldData = newWorldData;
		
		//delegate to helper function for rest of setup
		init();
	}
	
	/**
	 * Sets up a MapPanel.
	 * Helper function for the constructor.
	 * <p>
	 * (Assumes that worldData has been set previously.)
	 */
	private void init(){
		//set default values for what we're looking at
		currentView = Continent.WORLD;
		currentCountry = "none";
		currentMapMode = MapMode.ECONOMIC;
		
		//load data from the DataManager
		
	}
	
	/**
	 * Respond to events generated by the UI
	 * 
	 * @param e the ActionEvent that represents the event that occurred
	 */
	public void actionPerformed(ActionEvent e){
		System.out.println("Event " + e.toString() + " did the thing!");
	}
	
}
