package project;

import java.io.IOException;
import java.util.Random;
import java.util.Vector;

public class QuizRunner {
	private static final int TOTAL_QUESTIONS_TO_ASK = 10;
	private static final int MAX_ATTEMPTS_PER_QUESTION = 3;
	
	private String currentQuestion;
	private String currentCorrectAnswer;
	private int currentQuestionAttempts;
	
	private int currentQuestionNumber;
	private int questionsAnsweredCorrectly;
	//private String preTestTopic;
	private String currentTopic;
	private MapMode currentMode;
	//private boolean inPreTest;
	private boolean quizRunning;
	
	private Vector<String> questionsAsked;
	
	Vector<String> continentsToAskAboutByQuestion;
	
	private DataManager worldData;
	private MapPanel parent;//so we can change the continent shown when quizing across continents
	private StudentData student;
	
	/**
	 * Creates a new QuizRunner with the given parameters.
	 * 
	 * @param newParent the parent MapPanel of the QuizRunner
	 * @param newWorldData the DataManager that holds the data used for quizes
	 * @param newStudent the student whose viewing patterns guide the quiz
	 */
	public QuizRunner(MapPanel newParent, DataManager newWorldData, StudentData newStudent){
		worldData = newWorldData;
		parent = newParent;
		student = newStudent;
		
		//preTestTopic = student.getPreTestTopic();
		
		//inPreTest = false;
		quizRunning = false;
		
		questionsAsked = new Vector<String>();
	}
	
	/**
	 * Start a new quiz on the given topic and mode pair.
	 * 
	 * @param topic the continent (or world) to quiz upon
	 * @param mode whether the quiz should be on economics or health
	 */
	public void startQuiz(String topic, MapMode mode){
		//set state variables appropriately
		currentTopic = topic;
		currentMode = mode;
		
		quizRunning = true;
		
		currentQuestionNumber = 0;
		questionsAnsweredCorrectly = 0;
		
		//create a new blank vector
		questionsAsked = new Vector<String>();
		
		//if this quiz is on the world
		//work out which continent each question will ask about
		if(topic.equals("World")){
			//create a new blank vector
			continentsToAskAboutByQuestion = new Vector<String>();
			
			String[] continents = {"North America", "South America", "Europe", "Asia", "Africa", "Oceania"};
			
			//get a list of all the continents the student has seen countries within
			//ie that are fair game for quizzing
			Vector<String> continentsSeen = new Vector<String>();
			for(int i = 0; i < continents.length; i++){
				if(student.hasSeenCountriesInContinent(continents[i], currentMode)){
					continentsSeen.add(continents[i]);
				}
			}
			
			//how many questions to ask per continent
			int numQuestionsPerContinent = TOTAL_QUESTIONS_TO_ASK / continentsSeen.size();
			
			//fill in the vector
			for(int i = 0; i < continentsSeen.size(); i++){
				for(int j = 0; j < numQuestionsPerContinent; j++){
					continentsToAskAboutByQuestion.add(continentsSeen.get(i));
				}
			}
			
			//if the rounding on the division meant that we end up a question short
			//cover that
			if(continentsToAskAboutByQuestion.size() < TOTAL_QUESTIONS_TO_ASK){
				continentsToAskAboutByQuestion.add(continentsSeen.get(0));
			}
		}
		
	}
	
	/**
	 * Load a question. Contains logic for picking appropriate questions
	 * out of those generated by the countries.
	 */
	public void loadQuestion(){
		String prospectiveQuestion;
		
		Vector<String> countriesToAskAbout;
		
		if(!currentTopic.equals("World")){//only one continent, so things is easy
			//load a list of all the countries in the continent
			countriesToAskAbout = worldData.getDataForContinent(currentTopic).getCountryList();
			
			//entropy get!
			Random random = new Random();
			
			CountryData country;
			
			//get random countries out of the continent until we get one the student's seen
			while(true){
				country = worldData.getDataForCountry(countriesToAskAbout.get(random.nextInt(countriesToAskAbout.size())));
				
				//spin until we get a country they've seen
				if(student.hasCountryBeenSeen(country.getCountryName(), currentMode)){
					break;
				}
			}
			
			//generate random questions off of the chosen country until we get one we haven't asked before.
			while(true){
				prospectiveQuestion = ((currentMode == MapMode.HEALTH) ? country.generateHealthQuestion() : country.generateEconQuestion());
				
				//spin until we get a question we haven't asked yet
				if(!questionsAsked.contains(prospectiveQuestion)){
					questionsAsked.add(prospectiveQuestion);
					currentQuestion = prospectiveQuestion;
					currentCorrectAnswer = country.getCountryName();
					
					currentQuestionNumber++;
					currentQuestionAttempts = 0;
					
					break;
				}
			}
		} else {//the topic was world, so we'll pick a continent, then get a question about that continent
			//get the continent that this question is going to be about
			//spoofing currentTopic for the sake of the next call to loadQuestion()
			currentTopic = continentsToAskAboutByQuestion.get(currentQuestionNumber);
			
			try{
				parent.changeContinent(currentTopic);//make it so the user can see what's what
			} catch(IOException e){
				System.out.println("IOException in QuizRunner::loadQuestion(): " + e.getMessage());
			}
			
			//get the question
			loadQuestion();
			
			//revert the spoofing
			currentTopic = "World";
		}
		
		
	}
	
	/**
	 * Checks if the provided answer is the correct answer for the given question.
	 * 
	 * @param potentialAnswer the answer provided by the user
	 * @return whether or not the provided answer was correct
	 */
	public boolean checkAnswer(String potentialAnswer){
		currentQuestionAttempts++;
		
		boolean answerWasCorrect = potentialAnswer.equals(currentCorrectAnswer);
		
		if(answerWasCorrect){
			questionsAnsweredCorrectly++;
		}
		
		return answerWasCorrect;
	}
	
	/**
	 * End the currently running quiz
	 */
	public void endQuiz(){
		//set flags
		quizRunning = false;
		//inPreTest =  false;
	}
	
	/*public boolean getInPreTest(){
		return inPreTest;
	}*/
	
	/**
	 * Returns whether or not the QuizRunner is currently running a quiz.
	 * @return whether or not the QuizRunner is currently running a quiz
	 */
	public boolean getQuizRunning(){
		return quizRunning;
	}
	
	/**
	 * Loads an appropriate question and returns it.
	 * 
	 * @return 
	 */
	public String getQuestion(){
		//load a question
		loadQuestion();
		
		//give it back to the user
		return currentQuestion;
	}
	
	public boolean questionsRemainToAsk(){
		System.out.println("CQN: " + currentQuestionNumber);
		return currentQuestionNumber < TOTAL_QUESTIONS_TO_ASK;
	}
	
	public boolean hasRemainingAttempts(){
		return currentQuestionAttempts < MAX_ATTEMPTS_PER_QUESTION;
	}
	
	public int getRemainingAttempts(){
		return MAX_ATTEMPTS_PER_QUESTION - currentQuestionAttempts;
	}
	
	public String getQuizEndReport(){
		String report = "You answered " + questionsAnsweredCorrectly + " out of " + TOTAL_QUESTIONS_TO_ASK + " questions correctly";
		report += " and scored " + (int) ((((float) questionsAnsweredCorrectly) / ((float) TOTAL_QUESTIONS_TO_ASK)) * 100) + "%.";
		
		return report;
	}
}
